# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - nightly
services:
  - memcached
before_install:
  - if [ "$TRAVIS_OS_NAME" = osx ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = osx ]; then brew install memcached; fi
  - if [ "$TRAVIS_OS_NAME" = osx ]; then /usr/local/opt/memcached/bin/memcached -d; fi
notifications:
  email: false
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("Memcache"); Pkg.test("Memcache"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("Memcache")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder());'
